version: '3'

services:
  postgres:
    image: postgres:latest
    env_file:
      - .env
    ports:
      - "5432:5432"
  server:
    build:
      context: ./
      dockerfile: ./Dockerfile
      target: development
    command: pnpm start:dev
    env_file:
      - .env
    restart: always
    ports:
      - "8080:8080"
    volumes:
      - .:/usr/src/app
    deploy:
      mode: replicated
      replicas: 1
    depends_on:
      - postgres